meal/urls.py
from django.urls import path
from meal.views import (
    MealListView,
    MealDetailView,
    MealUpdateView,
    MealCreateView,
    MealDeleteView,
    about,
    CookListView,
    contact,
)


urlpatterns = [
    path("about/", about, name="about"),
    path("team/", CookListView.as_view(), name="team"),
    path("contact/", contact, name="contact"),
    path("menu/", MealListView.as_view(), name="menu"),
    path("create/", MealCreateView.as_view(), name="meal-create"),
    path("<slug:slug>/", MealDetailView.as_view(), name="meal-detail"),
    path("<slug:slug>/update/", MealUpdateView.as_view(), name="meal-update"),
    path("<slug:slug>/delete/", MealDeleteView.as_view(), name="meal-delete"),
]

app_name = "meal"

pet_project_restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from meal.views import index

urlpatterns = [
    path("", index, name="index"),
    path('admin/', admin.site.urls),
    path("meals/", include("meal.urls", namespace="meal")),
    path("users/", include("users.urls", namespace="users")),
    path("reservation/", include("reservation.urls", namespace="reservation")),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
     [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })])

reservation/urls.py
from django.urls import path
from reservation.views import (
    ReservationCreateView,
    ReservationListView,
    # ReservationDetailView,
)


urlpatterns = [
    path("", ReservationCreateView.as_view(), name="reservation"),
    path("list/", ReservationListView.as_view(), name="reservation-list"),
]

app_name = "reservation"

users/urls.py
from django.urls import path, include

from users.views import (
    UserCreateView,
    UserLoginView,
    UserLogoutView,
    UserUpdateView,
)

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path('registration/', UserCreateView.as_view(), name="registration"),
    path('update-data/<int:pk>/', UserUpdateView.as_view(), name="update-data"),
]

app_name = "users"

templates/includes/navbar.html
{% load static %}

<nav style="height: 98px" class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0 sticky-top shadow-sm">
  <a href="{% url 'index' %}" class="navbar-brand p-0">
    <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>FeastFlow</h1>
    <!-- <img src="{% static 'img/logo.png' %}" alt="Logo"> -->
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
    <span class="fa fa-bars"></span>
  </button>

  {% if user.is_authenticated %}
    <li class="nav-item nav-link">Hello <a href="{% url 'users:update-data' user.pk %}">{{ user.get_username }}</a></li> |
    <li class="nav-item nav-link"><a href="{% url 'users:logout'%}?next={{request.path}}">Sign-out</a></li>
  {% else %}
    <li class="nav-item nav-link"><a href="{% url 'users:login'%}?next={{request.path}}">Sign-in</a></li> |
    <li class="nav-item nav-link"><a href="{% url 'users:registration'%}?next={{request.path}}">Sign-up</a></li>
  {% endif %}

  <div class="collapse navbar-collapse" id="navbarCollapse">
    <div class="navbar-nav ms-auto py-0 pe-4">
      <a href="{% url 'index' %}" class="nav-item nav-link active">Home</a>
      <a href="{% url 'meal:menu' %}" class="nav-item nav-link">Menu</a>
      {% if user.is_authenticated %}
        <div class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">More</a>
          <div class="dropdown-menu m-0">
            <a href="#" class="dropdown-item">Account</a>
            {% if user.is_staff %}
              <a href="{% url 'reservation:reservation-list' %}" class="dropdown-item">Table reservation list</a>
            {% endif %}
          </div>
        </div>
      {% endif %}

      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">About Us</a>
        <div class="dropdown-menu m-0">
          <a href="{% url 'meal:about' %}" class="dropdown-item">About</a>
          <a href="{% url 'meal:team' %}" class="dropdown-item">Team</a>
          <a href="{% url 'meal:contact' %}" class="dropdown-item">Contact</a>
        </div>
      </div>
    </div>
    <a href="{% url 'reservation:reservation' %}" class="btn btn-primary py-2 px-4">Book A Table</a>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search.html
<form action="" method="get" class="custom-search-form">
  <div class="input-group">
    {{ search_form }}
    <button type="submit" class="btn btn-primary custom-search-button">
      <i class="fa fa-search"></i>
    </button>
  </div>
</form>