meal/urls.py
from django.urls import path
from meal.views import (
    MealListView,
    MealDetailView,
    MealUpdateView,
    MealCreateView,
    MealDeleteView,
    about,
    CookListView,
    contact,
)


urlpatterns = [
    path("about/", about, name="about"),
    path("team/", CookListView.as_view(), name="team"),
    path("contact/", contact, name="contact"),
    path("menu/", MealListView.as_view(), name="menu"),
    path("create/", MealCreateView.as_view(), name="meal-create"),
    path("<slug:slug>/", MealDetailView.as_view(), name="meal-detail"),
    path("<slug:slug>/update/", MealUpdateView.as_view(), name="meal-update"),
    path("<slug:slug>/delete/", MealDeleteView.as_view(), name="meal-delete"),
]

app_name = "meal"

pet_project_restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from meal.views import index

urlpatterns = [
    path("", index, name="index"),
    path('admin/', admin.site.urls),
    path("meals/", include("meal.urls", namespace="meal")),
    path("users/", include("users.urls", namespace="users")),
    path("reservation/", include("reservation.urls", namespace="reservation")),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
     [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })])

meal/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=50)
    fa_icon = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "categories"


class Meal(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(max_length=500)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preparation_time = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="meals")
    image = models.ImageField(upload_to="meal/")
    slug = models.SlugField(null=True, blank=True, unique=True)

    class Meta:
        ordering = ["name"]

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meal, self).save(
            force_insert=False, force_update=False, using=None, update_fields=None
        )

    def get_absolute_url(self):
        return reverse("meal:meal-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name


class Cook(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    about = models.TextField(max_length=150)
    position = models.CharField(max_length=50)
    image = models.ImageField(upload_to="cooker/")

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.position})"



meal/forms.py
from django import forms
from django.core.exceptions import ValidationError

from meal.models import Meal, Category


class MealForm(forms.ModelForm):

    name = forms.CharField(
        error_messages={
            "required": "*"
        },
        widget=forms.TextInput(attrs={
            "placeholder": "Name meal",
            "class": "form-control",
            "autofocus": True,
        }))

    description = forms.CharField(
        error_messages={
            "required": "*"
        },
        widget=forms.Textarea(attrs={
            "placeholder": "Description",
            "class": "form-control",
            "style": "height: 100px;"
        }))

    CHOICES = (
        (1, 'People 1'),
        (2, 'People 2'),
        (3, 'People 3'),
        (4, 'People 4'),
    )
    people = forms.ChoiceField(
        choices=CHOICES,
        error_messages={
            "required": "*"
        },
        widget=forms.Select(attrs={
                    "placeholder": "Count people",
                    "class": "form-select",
                })
    )

    price = forms.DecimalField(
        error_messages={
            "required": "*"
        },
        widget=forms.NumberInput(attrs={
            "placeholder": "Price",
            "class": "form-control",
        }))

    preparation_time = forms.IntegerField(
        error_messages={
            "required": "*"
        },
        widget=forms.NumberInput(attrs={
            "placeholder": "Price",
            "class": "form-control",
        }))

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        error_messages={
            "required": "*"
        },
        widget=forms.Select(attrs={
            "placeholder": "Category",
            "class": "form-select",
        })
    )

    image = forms.ImageField(
        error_messages={
            "required": "*"
        },
        widget=forms.ClearableFileInput(attrs={
        })
    )

    slug = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            "placeholder": "Slug",
            "class": "form-control",
        }))

    class Meta:
        model = Meal
        fields = (
            "name",
            "description",
            "people",
            "price",
            "preparation_time",
            "category",
            "image",
            "slug",
        )

    def clean_price(self):
        price = self.cleaned_data["price"]
        if price <= 0:
            raise ValidationError(" cannot be less than 0!")
        return price


class MealSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by name of meal..",
            "class": "form-control custom-search-input"
        })
    )

meal/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from meal.forms import MealForm, MealSearchForm
from meal.models import Meal, Cook, Category


class MealListView(generic.ListView):
    model = Meal
    template_name = "meal/menu.html"
    context_object_name = "meal_list"
    # paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MealListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = MealSearchForm(initial={
            "name": name
        })

        context["categories"] = Category.objects.all().order_by("pk")

        return context

    def get_queryset(self):
        queryset = Meal.objects.select_related("category")
        form = MealSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class MealDetailView(generic.DetailView):
    model = Meal
    template_name = "meal/meal_detail.html"


class MealUpdateView(UserPassesTestMixin, generic.UpdateView):
    model = Meal
    form_class = MealForm
    template_name = "meal/meal_form.html"

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_superuser


class MealCreateView(UserPassesTestMixin, generic.CreateView):
    model = Meal
    form_class = MealForm
    template_name = "meal/meal_form.html"
    success_url = reverse_lazy("meal:menu")

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_superuser


class MealDeleteView(UserPassesTestMixin, generic.DeleteView):
    model = Meal
    success_url = reverse_lazy("meal:menu")

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_superuser


class CookListView(generic.ListView):
    model = Cook
    template_name = "team.html"
    context_object_name = "cook_list"


def index(request):
    """View function for the home page of the site."""
    return render(request, "index.html")


def about(request):
    """View function for the about page of the site."""
    return render(request, "about.html")


def menu(request):
    """View function for the menu page of the site."""
    return render(request, "meal/menu.html")


def contact(request):
    """View function for the contact page of the site."""
    return render(request, "contact.html")

templates/meal/meal_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete meal?</h1>
  <form action="{% url 'meal:meal-delete' meal.slug %}" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/meal/meal_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}




  <div class="container-xxl py-5">
    <div class="container">
      <div class="row g-5 align-items-center">
        <div class="col-lg-6">
          <div class="row g-3">
            <img class="img-fluid rounded w-100 wow zoomIn " data-wow-delay="0.1s" src="{{ meal.image.url }}" style="object-fit: contain; width: 500px;">
          </div>
        </div>
        <div class="col-lg-6">

          {% if user.is_staff %}
            <form id="deleteForm" method="POST" action="{% url 'meal:meal-delete' meal.slug %}">
              {% csrf_token %}
              <button class="btn btn-outline-danger link-to-page" id="deleteButton" type="submit">Delete</button>
            </form>

            <a class="btn btn-outline-primary link-to-page" href="{% url 'meal:meal-update' meal.slug %}">Update</a>
          {% endif %}

          <h5 class="section-title ff-secondary text-start text-primary fw-normal">About meal</h5>
          <h1 class="mb-4">{{ meal.name }}</h1>
          <p class="mb-4">{{ meal.description }}</p>
          <p class="mb-4">This dish is for {{ meal.people }} {{ meal.people|pluralize:'person,people' }}</p>
          <div class="row g-4 mb-4">

            <div class="col-sm-6">
              <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">{{ meal.price }}</h1>
                <div class="ps-4">
                  <p class="mb-0">$</p>
                  <h6 class="text-uppercase mb-0">Price</h6>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">{{ meal.preparation_time }}</h1>
                <div class="ps-4">
                  <p class="mb-0">Time of</p>
                  <h6 class="text-uppercase mb-0">Preparation</h6>
                </div>
              </div>
            </div>
          </div>
{#          <a class="btn btn-primary py-3 px-5 mt-2" href="">Read More</a>#}
        </div>
      </div>
    </div>
  </div>




<!-- Modal window to confirm deletion -->
<div id="deleteModal" class="modal">
  <div class="modal-content">
    <h4>Confirm deletion</h4>
    <p>Are you sure you want to remove this meal?</p>
    <form id="confirmDeleteForm" method="POST" action="{% url 'meal:meal-delete' meal.slug %}">
      {% csrf_token %}
      <button class="btn btn-danger" id="confirmDeleteButton" type="submit">Delete</button>
      <button class="btn btn-secondary" id="cancelDeleteButton" type="button">Cancel</button>
    </form>
  </div>
</div>

<script>
  // Обработчик клика по кнопке удаления
  document.getElementById('deleteButton').addEventListener('click', function(event) {
    event.preventDefault(); // Отменяем обычную отправку формы
    document.getElementById('deleteModal').style.display = 'block'; // Показываем модальное окно
  });

  // Обработчик клика по кнопке отмены удаления в модальном окне
  document.getElementById('cancelDeleteButton').addEventListener('click', function(event) {
    event.preventDefault();
    document.getElementById('deleteModal').style.display = 'none'; // Скрываем модальное окно
  });
</script>

{% endblock %}

templates/meal/meal_form.html
{% extends "base.html" %}

{% block preview_after_navbar %}
{% endblock %}

{% block content %}

  <div class="row align-items-center g-5">
    <div class="container">
      <div class="row g-0">

        <div class="col-md-5 p-lg-3" >
          <div class="row g-3">
            <img class="img-fluid rounded w-100 wow zoomIn " data-wow-delay="0.1s" src="{{ meal.image.url }}" style="object-fit: contain; width: 500px; padding-top: 60px">
          </div>
        </div>

        <div class="col-md-6 d-flex align-items-center">
          <div class="p-5">
            <h3 class="section-title ff-secondary text-start text-primary fw-normal mb-4">{{ object|yesno:"Update,Create" }} meal</h3>


            <form method="post" action="" novalidate enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row g-3">
                <div class="col-md-6">
                  <div class="form-floating">
                    {{ form.name }}
                    <label for="{{ form.name.id_for_label }}">
                      Name
                      {% for error in form.name.errors %}
                        <span class="text-danger mb-4">{{ error }}</span>
                      {% endfor %}
                    </label>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-floating">
                    {{ form.price }}
                    <label for="{{ form.price.id_for_label }}">
                      Price
                      {% for error in form.price.errors %}
                        <span class="text-danger mb-4">{{ error }}</span>
                      {% endfor %}
                    </label>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-floating">
                    {{ form.description }}
                    <label for="{{ form.description.id_for_label }}">
                      Description
{#                      {% for error in form.description.errors %}#}
{#                        <span class="text-danger mb-4">{{ error }}</span>#}
{#                      {% endfor %}#}
                    </label>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-floating">
                    {{ form.people }}
                    <label for="{{ form.people.id_for_label }}">
                      No Of People
                    </label>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-floating">
                    {{ form.preparation_time }}
                    <label for="{{ form.preparation_time.id_for_label }}">
                      Time of preparation
                      {% if form.preparation_time.errors %}
                        <span class="text-danger mb-4">*</span>
                      {% endif %}
                    </label>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-floating">
                    {{ form.category }}
                    <label for="{{ form.category.id_for_label }}">
                      Category
                      {% for error in form.category.errors %}
                        <span class="text-danger mb-4">{{ error }}</span>
                      {% endfor %}
                    </label>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-floating">
                    {{ form.slug }}
                    <label for="{{ form.slug.id_for_label }}">
                      Slug
                    </label>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-floating ">
                    <div class="custom-clearable-file-input">
                      {{ form.image }}
                      <label for="{{ form.image.id_for_label }}">
                        {% for error in form.image.errors %}
                          <span class="text-danger mb-4">{{ error }}</span>
                        {% endfor %}
                      </label>
                    </div>
                  </div>
                </div>
                <div class="col-12">
                  <button class="btn btn-outline-primary w-100 py-3" type="submit">{{ object|yesno:"Ready,Create" }}</button>
                  <input type="hidden" name="next" value="{{ next }}" />
                </div>
              </div>
            </form>
          </div>
        </div>

        <div class="col-md-1">
        </div>

      </div>
    </div>
  </div>

{% endblock %}

templates/meal/menu.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>Menu</title>
{% endblock %}

{% block content %}
  <div class="container-xxl py-5">
    <div class="container">
      <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
        <h5 class="section-title ff-secondary text-center text-primary fw-normal">Food Menu</h5>
        <h1 class="mb-5">Most Popular Items</h1>
      </div>
      <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.1s">
        <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
          <li class="nav-item">
            <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-bs-toggle="pill" href="#All-menu">
              <i class="fa fa-book-open fa-2x text-primary"></i>
              <div class="ps-3">
                <h6 class="mt-n1 mb-0">ALL MENU</h6>
              </div>
            </a>
          </li>
          {% for category in categories %}
            <li class="nav-item">
              <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3" data-bs-toggle="pill" href="#{{ category }}">
                <i class="fa {{ category.fa_icon }} fa-2x text-primary"></i>
                <div class="ps-3">
                  <h6 class="mt-n1 mb-0">{{ category }}</h6>
                </div>
              </a>
            </li>
          {% endfor %}
        </ul>
        <div>
        {% include "includes/search.html" %}

        {% if user.is_staff %}
          <a class="btn btn-outline-primary" style="margin: 0; position: relative; left: 44%; bottom: 18px;" href="{% url 'meal:meal-create' %}">Create new meal</a>
        {% endif %}
        </div>

        <div class="tab-content">

          <div id="All-menu" class="tab-pane fade show p-0 active">
            <div class="row g-4">
              {% for meal in meal_list %}
                <div class="col-lg-6">
                  <a href="{% url 'meal:meal-detail' slug=meal.slug %}" style="color: #727272">
                    <div class="d-flex align-items-center">
                      <img class="flex-shrink-0 img-fluid rounded" src="{{ meal.image.url }}" alt="" style="width: 80px;">
                      <div class="w-100 d-flex flex-column text-start ps-4">
                        <h5 class="d-flex justify-content-between border-bottom pb-2">
                          <span>{{ meal.name }}</span>
                          <span class="text-primary">${{ meal.price }}</span>
                        </h5>
                        <small class="fst-italic">{{ meal.description }}</small>
                      </div>
                    </div>
                  </a>
                </div>
              {% endfor %}
            </div>
          </div>

          {% for category in categories %}
            <div id="{{ category }}" class="tab-pane fade show p-0">
                <div class="row g-4">
                  {% for meal in meal_list %}
                    {% if meal.category.name == category.name %}
                      <div class="col-lg-6">
                        <a href="{% url 'meal:meal-detail' slug=meal.slug %}" style="color: #727272">
                          <div class="d-flex align-items-center">
                            <img class="flex-shrink-0 img-fluid rounded" src="{{ meal.image.url }}" alt="" style="width: 80px;">
                            <div class="w-100 d-flex flex-column text-start ps-4">
                              <h5 class="d-flex justify-content-between border-bottom pb-2">
                                <span>{{ meal.name }}</span>
                                <span class="text-primary">${{ meal.price }}</span>
                              </h5>
                              <small class="fst-italic">{{ meal.description }}</small>
                            </div>
                          </div>
                        </a>
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
            </div>
          {% endfor %}
        </div>

        <div class="nav nav-pills d-inline-flex justify-content-center mb-5 mt-5">
          {% include "includes/pagination.html" %}
        </div>

      </div>
    </div>
  </div>

{% endblock content %}