meal/urls.py
from django.urls import path
from meal.views import (
    MealListView,
    MealDetailView,
    MealUpdateView,
    MealCreateView,
    MealDeleteView,
    about,
    CookListView,
    contact,
)


urlpatterns = [
    path("about/", about, name="about"),
    path("team/", CookListView.as_view(), name="team"),
    path("contact/", contact, name="contact"),
    path("menu/", MealListView.as_view(), name="menu"),
    path("create/", MealCreateView.as_view(), name="meal-create"),
    path("<slug:slug>/", MealDetailView.as_view(), name="meal-detail"),
    path("<slug:slug>/update/", MealUpdateView.as_view(), name="meal-update"),
    path("<slug:slug>/delete/", MealDeleteView.as_view(), name="meal-delete"),
]

app_name = "meal"

pet_project_restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from meal.views import index

urlpatterns = [
    path("", index, name="index"),
    path('admin/', admin.site.urls),
    path("meals/", include("meal.urls", namespace="meal")),
    path("users/", include("users.urls", namespace="users")),
    path("reservation/", include("reservation.urls", namespace="reservation")),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
     [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })])

reservation/urls.py
from django.urls import path
from reservation.views import (
    ReservationCreateView,
    ReservationListView,
    # ReservationDetailView,
)


urlpatterns = [
    path("", ReservationCreateView.as_view(), name="reservation"),
    path("list/", ReservationListView.as_view(), name="reservation-list"),
]

app_name = "reservation"

meal/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=50)
    fa_icon = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "categories"


class Meal(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(max_length=500)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preparation_time = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="meals")
    image = models.ImageField(upload_to="meal/")
    slug = models.SlugField(null=True, blank=True, unique=True)

    class Meta:
        ordering = ["name"]

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meal, self).save(
            force_insert=False, force_update=False, using=None, update_fields=None
        )

    def get_absolute_url(self):
        return reverse("meal:meal-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name


class Cook(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    about = models.TextField(max_length=150)
    position = models.CharField(max_length=50)
    image = models.ImageField(upload_to="cooker/")

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.position})"



templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- About Start -->
  <div class="container-xxl py-5">
    <div class="container">
      <div class="row g-5 align-items-center">
        <div class="col-lg-6">
          <div class="row g-3">
            <div class="col-6 text-start">
              <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.1s" src="{% static 'img/about-1.jpg' %}">
            </div>
            <div class="col-6 text-start">
              <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.3s" src="{% static 'img/about-2.jpg' %}" style="margin-top: 25%;">
            </div>
            <div class="col-6 text-end">
              <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.5s" src="{% static 'img/about-3.jpg' %}">
            </div>
            <div class="col-6 text-end">
              <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.7s" src="{% static 'img/about-4.jpg' %}">
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <h5 class="section-title ff-secondary text-start text-primary fw-normal">About Us</h5>
          <h1 class="mb-4">Welcome to <i class="fa fa-utensils text-primary me-2"></i>Restoran</h1>
          <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos erat ipsum et lorem et sit, sed stet lorem sit.</p>
          <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
          <div class="row g-4 mb-4">
            <div class="col-sm-6">
              <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">15</h1>
                <div class="ps-4">
                  <p class="mb-0">Years of</p>
                  <h6 class="text-uppercase mb-0">Experience</h6>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">50</h1>
                <div class="ps-4">
                  <p class="mb-0">Popular</p>
                  <h6 class="text-uppercase mb-0">Master Chefs</h6>
                </div>
              </div>
            </div>
          </div>
          <a class="btn btn-primary py-3 px-5 mt-2" href="">Read More</a>
        </div>
      </div>
    </div>
  </div>
  <!-- About End -->

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    {% block title %}
      <title>FeastFlow</title>
    {% endblock title %}
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/logo.png' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="stylesheet" href="{% static 'lib/animate/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}">

    <!-- Customized Bootstrap Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Template Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <div class="container-xxl bg-white p-0">
      {% block spinner %}
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
          <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
        <!-- Spinner End -->
      {% endblock spinner %}


        <!-- Navbar & Hero Start -->

        <div class="container-xxl position-relative p-0">

          {% block navbar %}
            {% include "includes/navbar.html" %}
          {% endblock navbar %}


          <div class="container-xxl py-5 bg-dark hero-header mb-5">
            {% block preview_after_navbar %}
            {% endblock preview_after_navbar %}
          </div>

        </div>
        <!-- Navbar & Hero End -->



      {% block content %}
      {% endblock content %}
        
      {% block footer %}
        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                        <a class="btn btn-link" href="">About Us</a>
                        <a class="btn btn-link" href="">Contact Us</a>
                        <a class="btn btn-link" href="">Reservation</a>
                        <a class="btn btn-link" href="">Privacy Policy</a>
                        <a class="btn btn-link" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                        <h5 class="text-light fw-normal">Monday - Saturday</h5>
                        <p>09AM - 09PM</p>
                        <h5 class="text-light fw-normal">Sunday</h5>
                        <p>10AM - 08PM</p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="{% url 'meal:about' %}">Restaurant</a>, All Right Reserved.
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="{% url 'index' %}">Home</a>
                                <a href="{% url 'meal:team' %}">Cookies</a>
                                <a href="{% url 'meal:contact' %}">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
      {% endblock footer %}

      {% block back_to_top %}
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
      {% endblock back_to_top %}

    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}


{% block preview_after_navbar %}
  <div class="container my-5 py-5">
    <div class="row align-items-center g-5">
      <div class="col-lg-6 text-center text-lg-start">
        <h1 class="display-3 text-white animated slideInLeft">Enjoy Our<br>Delicious Meal</h1>
        <p class="text-white animated slideInLeft mb-4 pb-2">The restaurant industry is one of the largest components of the hospitality industry. It is focused on providing food services where customers can order food and eat it on the premises. In this complete guide, you can learn more about the restaurant industry, how it is defined, the different types of restaurants that exist, how the restaurant industry differs from the food service industry, and much more.</p>
        <a href="{% url 'reservation:reservation' %}" class="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft">Book A Table</a>
      </div>
      <div class="col-lg-6 text-center text-lg-end overflow-hidden">
        <img class="img-fluid" src="{% static 'img/hero1.png' %}" alt="Dish">
      </div>
    </div>
  </div>
{% endblock preview_after_navbar %}

{% block content %}
  {% block service %}
    <!-- Service Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-4">
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="service-item rounded pt-3">
                        <div class="p-4">
                            <i class="fa fa-3x fa-user-tie text-primary mb-4"></i>
                            <h5>Master Chefs</h5>
                            <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                    <div class="service-item rounded pt-3">
                        <div class="p-4">
                            <i class="fa fa-3x fa-utensils text-primary mb-4"></i>
                            <h5>Quality Food</h5>
                            <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                    <div class="service-item rounded pt-3">
                        <div class="p-4">
                            <i class="fa fa-3x fa-cart-plus text-primary mb-4"></i>
                            <h5>Online Order</h5>
                            <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                    <div class="service-item rounded pt-3">
                        <div class="p-4">
                            <i class="fa fa-3x fa-headset text-primary mb-4"></i>
                            <h5>24/7 Service</h5>
                            <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Service End -->
  {% endblock service %}

  {% block about %}
    <!-- About Start -->
    <div class="container-xxl py-5">
      <div class="container">
        <div class="row g-5 align-items-center">
          <div class="col-lg-6">
            <div class="row g-3">
              <div class="col-6 text-start">
                <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.1s" src="{% static 'img/about-1.jpg' %}">
              </div>
              <div class="col-6 text-start">
                <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.3s" src="{% static 'img/about-2.jpg' %}" style="margin-top: 25%;">
              </div>
              <div class="col-6 text-end">
                <img class="img-fluid rounded w-75 wow zoomIn" data-wow-delay="0.5s" src="{% static 'img/about-3.jpg' %}">
              </div>
              <div class="col-6 text-end">
                <img class="img-fluid rounded w-100 wow zoomIn" data-wow-delay="0.7s" src="{% static 'img/about-4.jpg' %}">
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <h5 class="section-title ff-secondary text-start text-primary fw-normal">About Us</h5>
            <h1 class="mb-4">Welcome to <i class="fa fa-utensils text-primary me-2"></i>Restoran</h1>
            <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos erat ipsum et lorem et sit, sed stet lorem sit.</p>
            <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
            <div class="row g-4 mb-4">
              <div class="col-sm-6">
                <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                  <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">15</h1>
                  <div class="ps-4">
                    <p class="mb-0">Years of</p>
                    <h6 class="text-uppercase mb-0">Experience</h6>
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                  <h1 class="flex-shrink-0 display-5 text-primary mb-0" data-toggle="counter-up">50</h1>
                  <div class="ps-4">
                    <p class="mb-0">Popular</p>
                    <h6 class="text-uppercase mb-0">Master Chefs</h6>
                  </div>
                </div>
              </div>
            </div>
            <a class="btn btn-primary py-3 px-5 mt-2" href="">Read More</a>
          </div>
        </div>
      </div>
    </div>
    <!-- About End -->
  {% endblock about %}


  {% block testimonial %}
    <!-- Testimonial Start -->
    <div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="text-center">
                <h5 class="section-title ff-secondary text-center text-primary fw-normal">Testimonial</h5>
                <h1 class="mb-5">Our Clients Say!!!</h1>
            </div>
            <div class="owl-carousel testimonial-carousel">
                <div class="testimonial-item bg-transparent border rounded p-4">
                    <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                    <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                    <div class="d-flex align-items-center">
                        <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-1.jpg' %}" style="width: 50px; height: 50px;">
                        <div class="ps-3">
                            <h5 class="mb-1">Client Name</h5>
                            <small>Profession</small>
                        </div>
                    </div>
                </div>
                <div class="testimonial-item bg-transparent border rounded p-4">
                    <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                    <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                    <div class="d-flex align-items-center">
                        <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-2.jpg' %}" style="width: 50px; height: 50px;">
                        <div class="ps-3">
                            <h5 class="mb-1">Client Name</h5>
                            <small>Profession</small>
                        </div>
                    </div>
                </div>
                <div class="testimonial-item bg-transparent border rounded p-4">
                    <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                    <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                    <div class="d-flex align-items-center">
                        <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-3.jpg' %}" style="width: 50px; height: 50px;">
                        <div class="ps-3">
                            <h5 class="mb-1">Client Name</h5>
                            <small>Profession</small>
                        </div>
                    </div>
                </div>
                <div class="testimonial-item bg-transparent border rounded p-4">
                    <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                    <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                    <div class="d-flex align-items-center">
                        <img class="img-fluid flex-shrink-0 rounded-circle" src="{% static 'img/testimonial-4.jpg' %}" style="width: 50px; height: 50px;">
                        <div class="ps-3">
                            <h5 class="mb-1">Client Name</h5>
                            <small>Profession</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Testimonial End -->
  {% endblock testimonial %}
{% endblock content %}

templates/menu.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>Menu</title>
{% endblock %}

{% block content %}
  <div class="container-xxl py-5">
    <div class="container">
      <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
        <h5 class="section-title ff-secondary text-center text-primary fw-normal">Food Menu</h5>
        <h1 class="mb-5">Most Popular Items</h1>
      </div>
      <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.1s">
        <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
          <li class="nav-item">
            <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-bs-toggle="pill" href="#tab-1">
              <i class="fa fa-coffee fa-2x text-primary"></i>
              <div class="ps-3">
                <small class="text-body">Popular</small>
                <h6 class="mt-n1 mb-0">Breakfast</h6>
              </div>
            </a>
          </li>
          <li class="nav-item">
            <a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-2">
              <i class="fa fa-pizza-slice fa-2x text-primary"></i>
              <div class="ps-3">
                <small class="text-body">Special</small>
                <h6 class="mt-n1 mb-0">Launch</h6>
              </div>
            </a>
          </li>
          <li class="nav-item">
            <a class="d-flex align-items-center text-start mx-3 me-0 pb-3" data-bs-toggle="pill" href="#tab-3">
              <i class="fa fa-utensils fa-2x text-primary"></i>
              <div class="ps-3">
                <small class="text-body">Lovely</small>
                <h6 class="mt-n1 mb-0">Dinner</h6>
              </div>
            </a>
          </li>
        </ul>
      <div class="tab-content">
          <div id="tab-1" class="tab-pane fade show p-0 active">
              <div class="row g-4">

                {% for meal in meal_list %}

                  <div class="col-lg-6">
                    <a href="{% url 'meal:meal-detail' slug=meal.slug %}" style="color: #727272">
                      <div class="d-flex align-items-center">
                        <img class="flex-shrink-0 img-fluid rounded" src="{{ meal.image.url }}" alt="" style="width: 80px;">
                        <div class="w-100 d-flex flex-column text-start ps-4">
                          <h5 class="d-flex justify-content-between border-bottom pb-2">
                            <span>{{ meal.name }}</span>
                            <span class="text-primary">${{ meal.price }}</span>
                          </h5>
                          <small class="fst-italic">{{ meal.description }}</small>
                        </div>
                      </div>
                    </a>
                  </div>

                {% endfor %}

              </div>
          </div>
          <div id="tab-2" class="tab-pane fade show p-0">
              <div class="row g-4">
                {% for meal in meal_list %}
                  {% if meal.category.name == "Pizza" %}
                    <a href="#">
                      <div class="col-lg-6">
                        <div class="d-flex align-items-center">
                          <img class="flex-shrink-0 img-fluid rounded" src="{{ meal.image.url }}" alt="" style="width: 80px;">
                          <div class="w-100 d-flex flex-column text-start ps-4">
                            <h5 class="d-flex justify-content-between border-bottom pb-2">
                              <span>{{ meal.name }}</span>
                              <span class="text-primary">${{ meal.price }}</span>
                            </h5>
                            <small class="fst-italic">{{ meal.description }}</small>
                          </div>
                        </div>
                      </div>
                    </a>

                  {% endif %}
                {% endfor %}

              </div>
          </div>
          <div id="tab-3" class="tab-pane fade show p-0">
              <div class="row g-4">

              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/team.html
{% extends "base.html" %}

{% block content %}
  <!-- Team Start -->
  <div class="container-xxl pt-5 pb-3">
    <div class="container">
      <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
        <h5 class="section-title ff-secondary text-center text-primary fw-normal">Team Members</h5>
        <h1 class="mb-5">Our Master Chefs</h1>
      </div>
      <div class="row g-4">

        {% for cook in cook_list %}
          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="team-item text-center rounded overflow-hidden">
              <div class="rounded-circle overflow-hidden m-4">
                <img class="img-fluid" src="{{ cook.image.url }}" alt="">
              </div>
              <h5 class="mb-0">{{ cook.first_name }} {{ cook.last_name }}</h5>
              <small>{{ cook.position }}</small>
              <div class="d-flex justify-content-center mt-3">
                <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-twitter"></i></a>
                <a class="btn btn-square btn-primary mx-1" href=""><i class="fab fa-instagram"></i></a>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>
  <!-- Team End -->`
{% endblock content %}